name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew app:build

      - name: Run tests
        run: ./gradlew app:test

      # Create APK

      - name: Assemble APK release
        run: ./gradlew app:assembleRelease

      - name: Assemble APK debug
        run: ./gradlew app:assembleDebug

      # Upload Artifact Build

      - name: Upload APK release artifact
        uses: actions/upload-artifact@v4
        with:
          name: rnm-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload APK debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: rnm-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk